### PR TITLE
RecyclerView displays real data from API

### PR DESCRIPTION
**Pull request by s-kettle**
- Multiple UI tweaks
- Main view now displays data pulled from the real API database

### CODE REVIEW

**Comment by Lonrot** [comment]
@s-kettle Do you need review or is the recyclerview still broken?

**Comment by s-kettle** [comment]
Still broken. My other PR needs reviewing still though.

**Comment by s-kettle** [comment]
The recycler view issue is now fixed, this can be reviewed as normal now and merged.

**Review by Lonrot — APPROVED** [review]
Very nice fix :+1: from what I can see before, It was trying to load an image with no data?

**Pull request merged**
